//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrensCreativity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChildrenCreativityEntities : DbContext
    {

        private static ChildrenCreativityEntities _context;

        public static ChildrenCreativityEntities GetContext()
        {
            if (_context == null)
                _context = new ChildrenCreativityEntities();
            return _context;
        }

        public ChildrenCreativityEntities()
            : base("name=ChildrenCreativityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<delivery_points> delivery_points { get; set; }
        public virtual DbSet<order_bins> order_bins { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<producers> producers { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<user_roles> user_roles { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
