//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrensCreativity
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_bins
    {
        public int order_bin_id { get; set; }
        public int fk_order_id { get; set; }
        public int fk_product_id { get; set; }
        public int order_bin_count { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
