//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrensCreativity
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.order_bins = new HashSet<order_bins>();
        }
    
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> order_delivery_date { get; set; }
        public Nullable<int> order_code { get; set; }
        public string order_status { get; set; }
        public Nullable<int> fk_delivery_point_id { get; set; }
        public Nullable<int> fk_user_id { get; set; }
        public Nullable<double> order_sum { get; set; }
    
        public virtual delivery_points delivery_points { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_bins> order_bins { get; set; }
        public virtual users users { get; set; }
    }
}
