//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrensCreativity
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.order_bins = new HashSet<order_bins>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_desc { get; set; }
        public double product_price { get; set; }
        public Nullable<int> product_discount { get; set; }
        public int product_count { get; set; }
        public byte[] product_photo { get; set; }
        public int fk_producer_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_bins> order_bins { get; set; }
        public virtual producers producers { get; set; }
    }
}
